

services:

  mysqlservice:
    image: mysql:8.4
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=hola123
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
    volumes:
      - ./my/own/datadir:/var/lib/mysql